"""Runtime subsystem public facade.

Implementation lives in focused modules under this package. This facade keeps
the historical ``cc_branch.runtime`` import path stable.
"""

from __future__ import annotations

from .backends import Backend, TmuxBackend, get_backend, set_backend
from .capabilities import (
    RUNTIME_CAPABILITIES,
    TERMINAL_RUNTIME,
    TMUX_RUNTIME,
    RuntimeCapabilities,
    RuntimeId,
    external_process_slots,
    is_external_process_runtime,
    is_known_runtime,
    is_managed_runtime,
    managed_slots,
    runtime_capabilities,
    supports_attach,
    supports_background_start,
    supports_dashboard,
    supports_stop,
    supports_windows,
)
from .execution import (
    POST_LAUNCH_DELAY,
    _dashboard_layout,
    _dashboard_session_name,
    _ensure_terminal_slot,
    _ensure_window,
    _kill_dashboard,
    _list_window_names,
    apply_workspace,
    attach_slot,
    build_status_data,
    ensure_slot,
    format_status,
    open_command,
    open_dashboard,
    restart_workspace,
    send_keys,
    stop_extra_windows,
    stop_workspace,
    subprocess,
    tmux_has_session,
    tmux_has_window,
    which,
)
from .shells import tmux_attach_shell_command

__all__ = [
    "Backend",
    "RUNTIME_CAPABILITIES",
    "RuntimeCapabilities",
    "RuntimeId",
    "TERMINAL_RUNTIME",
    "TMUX_RUNTIME",
    "TmuxBackend",
    "POST_LAUNCH_DELAY",
    "_dashboard_layout",
    "_dashboard_session_name",
    "_ensure_terminal_slot",
    "_ensure_window",
    "_kill_dashboard",
    "_list_window_names",
    "apply_workspace",
    "attach_slot",
    "build_status_data",
    "ensure_slot",
    "external_process_slots",
    "format_status",
    "get_backend",
    "is_external_process_runtime",
    "is_known_runtime",
    "is_managed_runtime",
    "managed_slots",
    "open_command",
    "open_dashboard",
    "restart_workspace",
    "runtime_capabilities",
    "send_keys",
    "set_backend",
    "stop_extra_windows",
    "stop_workspace",
    "subprocess",
    "supports_attach",
    "supports_background_start",
    "supports_dashboard",
    "supports_stop",
    "supports_windows",
    "tmux_has_session",
    "tmux_has_window",
    "tmux_attach_shell_command",
    "which",
]
